---
- hosts: all
  roles:
    - role: '{{playbook_dir}}'
  tasks:
    - command: /usr/local/kibana/bin/kibana --allow-root --version
      register: kibana_test_output
    - debug:
        msg: '{{ kibana_test_output.stdout }}'
