---
- name: Testing andrewrothstein.kibana
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'kibana --allow-root --version'
      ansible.builtin.command: sh -lc 'kibana --allow-root --version'
      changed_when: false
      register: kibana_test_output
    - name: Output of 'kibana --allow-root --version'
      ansible.builtin.debug:
        msg: '{{ kibana_test_output.stdout }}'
